@startuml
|#LightBlue|Покупатель|
start
:Открывает главную страницу Авито.Кухня;
:Ищет заведения (фильтр по кухне/рейтингу);
:Выбирает ресторан и просматривает меню;
:Добавляет позиции в корзину (указывает кол-во);
:Вводит адрес доставки и комментарий к заказу;
:Нажимает "Оформить заказ";

if (Все позиции есть в наличии?) then (Да)
  :Заказ создан. Видит статус: "Принят";
  :Собираем заказ. Видит статус: "Собран"
  :Отслеживает статус: "Готовится" -> "Передан курьеру";
  :Получает заказ;
  stop
else (Нет)
  :Видит сообщение об ошибке (товара нет);
  :Корректирует корзину;
  backward:Возврат к редактированию;
endif
@enduml
