@startuml
|#LightGreen|Ресторан / Менеджер|
start
:Получает доступ к закрытому кабинету;
:Заполняет информацию о ресторане (адрес, часы работы);
:Добавляет/редактирует позиции меню (цены, фото, наличие);
:Ожидает поступление новых заказов;

while (Рабочий день) is (Проверка заказов)
  :Получает уведомление о новом заказе;
  :Подтверждает заказ (меняет статус "В работе");
  :Готовит заказ;
  :Переводит статус в "Готов к выдаче";
  :Передает курьеру;
endwhile (Конец смены)

stop
@enduml
